fix: remove inline dependencies from `build_datapackage.py`
No longer needed since we have `pyproject.toml`
Resolves an error I got while trying to run the script:

```cmd
>>> uv run scripts/build_datapackage.py
```

```py
Traceback (most recent call last):
  File "../vega-datasets/scripts/build_datapackage.py", line 60, in <module>
    import niquests
ModuleNotFoundError: No module named 'niquests'
```